(define (problem labyrinthProblem)
    (:domain labyrinth)
    (:objects minotaur theseus r1 r2 r3 r4 r5 r6 r7 c1 c2 c3 c4 c5 c6 c7 c8)
    (:init (isMinotaur minotaur) (isTheseus theseus)
            (nextr r1 r2) (nextr r2 r3) (nextr r3 r4) (nextr r4 r5) (nextr r5 r6) (nextr r6 r7)
            (nextc c1 c2) (nextc c2 c3) (nextc c3 c4) (nextc c4 c5) (nextc c5 c6) (nextc c6 c7) (nextc c7 c8)
            (wallAt r1 c1) (wallAt r1 c2) (wallAt r1 c3) (wallAt r1 c4) (wallAt r1 c5) (wallAt r1 c6) (wallAt r1 c7) (wallAt r1 c8)
             (wallAt r2 c1) (wallAt r3 c1) (wallAt r4 c1) (wallAt r5 c1) (wallAt r6 c1) (wallAt r7 c1)
              (wallAt r7 c2) (wallAt r7 c3) (wallAt r7 c4) (wallAt r7 c6) (wallAt r7 c7) (wallAt r7 c8)
               (wallAt r6 c8) (wallAt r5 c8) (wallAt r4 c8) (wallAt r3 c8) (wallAt r2 c8)
                (wallAt r5 c3) (wallAt r4 c3) (wallAt r3 c3) (wallAt r3 c4) (wallAt r3 c5) (wallAt r3 c7) (wallAt r5 c5) (wallAt r5 c6) (wallAt r5 c7)
            (not(theseusVisited r2 c2))
            (not(theseusVisited r2 c3))
            (not(theseusVisited r2 c4))
            (not(theseusVisited r2 c5))
            (theseusVisited r2 c6)
            (not(theseusVisited r2 c7))
            (not(theseusVisited r3 c2))
            (not(theseusVisited r3 c6))
            (not(theseusVisited r4 c2))
            (not(theseusVisited r4 c4))
            (not(theseusVisited r4 c5))
            (not(theseusVisited r4 c6))
            (not(theseusVisited r4 c7))
            (not(theseusVisited r5 c2))
            (not(theseusVisited r5 c4))
            (not(theseusVisited r6 c2))
            (not(theseusVisited r6 c3))
            (not(theseusVisited r6 c4))
            (not(theseusVisited r6 c5))
            (not(theseusVisited r6 c6))
            (not(theseusVisited r6 c7))
            (justMoved minotaur)
            (not(justMoved theseus))
            (characterAt minotaur r2 c7)
            (characterAt theseus r7 c5)
    )
    (:goal (or (characterAt minotaur r7 c5) 
            (and 
            (theseusVisited r2 c2)
            (theseusVisited r2 c3)
            (theseusVisited r2 c4)
            (theseusVisited r2 c5)
            (theseusVisited r2 c6)
            (theseusVisited r2 c7)
            (theseusVisited r3 c2)
            (theseusVisited r3 c6)
            (theseusVisited r4 c2)
            (theseusVisited r4 c4)
            (theseusVisited r4 c5)
            (theseusVisited r4 c6)
            (theseusVisited r4 c7)
            (theseusVisited r5 c2)
            (theseusVisited r5 c4)
            (theseusVisited r6 c2)
            (theseusVisited r6 c3)
            (theseusVisited r6 c4)
            (theseusVisited r6 c5)
            (theseusVisited r6 c6)
            (theseusVisited r6 c7))
            )
    )
)